# Generated by Django 4.0 on 2021-12-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('imageUrl', models.ImageField(blank=True, upload_to='images/')),
                ('newsSite', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=255)),
                ('publishedAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('featured', models.BooleanField()),
                ('events', models.ForeignKey(default=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='voos.events')),
                ('launches', models.ForeignKey(default=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='voos.launch')),
            ],
        ),
    ]
