# Generated by Django 4.0 on 2021-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='launch',
            options={'verbose_name': 'Launch', 'verbose_name_plural': 'Launchs'},
        ),
        migrations.AlterField(
            model_name='voo',
            name='imageUrl',
            field=models.URLField(),
        ),
    ]
