# Generated by Django 4.0 on 2021-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0002_alter_events_options_alter_launch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
