# Generated by Django 4.0 on 2021-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0003_voo_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='key',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
