# Generated by Django 4.0 on 2021-12-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0005_alter_voo_events_alter_voo_launches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voo',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='newsSite',
            new_name='news_site',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='publishedAt',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
