# Generated by Django 4.0 on 2021-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0006_rename_imageurl_voo_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='provider',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='provider',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
