# Generated by Django 4.0 on 2021-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0007_alter_events_key_alter_events_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voo',
            name='news_site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='voo',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
