# Generated by Django 4.0 on 2021-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0008_alter_voo_image_url_alter_voo_news_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='summary',
            field=models.TextField(),
        ),
    ]
