# Generated by Django 4.0 on 2021-12-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0009_alter_voo_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='provider',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
