# Generated by Django 4.0 on 2021-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0011_remove_voo_launches'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='launches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
