# Generated by Django 4.0 on 2021-12-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0012_voo_launches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Launch',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='events',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
